package channels

type Normal struct {
	Origin  string
	Various []string
	Use     bool
}

/**
Сюда добавляются все каналы, которые должны быть воспроизведены
*/

var Normales = map[int]*Normal{
	1:   &Normal{Use: true, Origin: "RT Документальный HD", Various: []string{"RT Документальный HD"}},
	2:   &Normal{Use: true, Origin: "Губерния 33 (Владимир)", Various: []string{"Губерния 33 (Владимир)"}},
	3:   &Normal{Use: true, Origin: "Малятко TV", Various: []string{"Малятко TV"}},
	4:   &Normal{Use: true, Origin: "Регион 29 (Архангельск)", Various: []string{"Регион 29 (Архангельск)"}},
	5:   &Normal{Use: true, Origin: "Сказки Зайки", Various: []string{"Сказки Зайки"}},
	6:   &Normal{Use: true, Origin: "Черновицкий Проминь HD", Various: []string{"Черновицкий Проминь HD"}},
	7:   &Normal{Use: true, Origin: "Odessa Int.", Various: []string{"Odessa Int."}},
	8:   &Normal{Use: true, Origin: "UA Харьков", Various: []string{"UA Харьков"}},
	9:   &Normal{Use: true, Origin: "Архыз 24 HD", Various: []string{"Архыз 24 HD"}},
	10:  &Normal{Use: true, Origin: "Мир (HD)", Various: []string{"Мир (HD)"}},
	11:  &Normal{Use: true, Origin: "Мир Белогорья", Various: []string{"Мир Белогорья"}},
	12:  &Normal{Use: true, Origin: "Тернополь 1", Various: []string{"Тернополь 1"}},
	13:  &Normal{Use: true, Origin: "Bridge TV Hits", Various: []string{"Bridge TV Hits"}},
	14:  &Normal{Use: true, Origin: "RT HD", Various: []string{"RT HD"}},
	15:  &Normal{Use: true, Origin: "Ника TV (Калуга)", Various: []string{"Ника TV (Калуга)"}},
	16:  &Normal{Use: true, Origin: "Россия 1 (Кабардино-Балкария)", Various: []string{"Россия 1 (Кабардино-Балкария)"}},
	17:  &Normal{Use: true, Origin: "UA Закарпатье", Various: []string{"UA Закарпатье"}},
	18:  &Normal{Use: true, Origin: "Ростов-папа HD", Various: []string{"Ростов-папа HD"}},
	19:  &Normal{Use: true, Origin: "Беларусь 4 (Витебск)", Various: []string{"Беларусь 4 (Витебск)"}},
	20:  &Normal{Use: true, Origin: "ЛенТВ 24", Various: []string{"ЛенТВ 24"}},
	21:  &Normal{Use: true, Origin: "Мир Premium HD", Various: []string{"Мир Premium HD"}},
	22:  &Normal{Use: true, Origin: "Первый канал Евразия", Various: []string{"Первый канал Евразия"}},
	23:  &Normal{Use: true, Origin: "Эхо ТВ", Various: []string{"Эхо ТВ"}},
	24:  &Normal{Use: true, Origin: "Грозный ТВ", Various: []string{"Грозный ТВ"}},
	25:  &Normal{Use: true, Origin: "СТС International", Various: []string{"СТС International"}},
	26:  &Normal{Use: true, Origin: "Саратов 24", Various: []string{"Саратов 24"}},
	27:  &Normal{Use: true, Origin: "Тамыр", Various: []string{"Тамыр"}},
	28:  &Normal{Use: true, Origin: "UA Крым", Various: []string{"UA Крым"}},
	29:  &Normal{Use: true, Origin: "Наши Города", Various: []string{"Наши Города"}},
	30:  &Normal{Use: true, Origin: "112 Украина", Various: []string{"112 Украина"}},
	31:  &Normal{Use: true, Origin: "Ritsa TV", Various: []string{"Ritsa TV"}},
	32:  &Normal{Use: true, Origin: "Между.Net ТВ HD (Междуреченск)", Various: []string{"Между.Net ТВ HD (Междуреченск)"}},
	33:  &Normal{Use: true, Origin: "Тивиком (Улан-Удэ)", Various: []string{"Тивиком (Улан-Удэ)"}},
	34:  &Normal{Use: true, Origin: "Югра ТВ", Various: []string{"Югра ТВ"}},
	35:  &Normal{Use: true, Origin: "AD SPORT 2 HD", Various: []string{"AD SPORT 2 HD"}},
	36:  &Normal{Use: true, Origin: "FILM TV", Various: []string{"FILM TV"}},
	37:  &Normal{Use: true, Origin: "UA Карпаты", Various: []string{"UA Карпаты"}},
	38:  &Normal{Use: true, Origin: "ТРК Ильдана (Черкассы)", Various: []string{"ТРК Ильдана (Черкассы)"}},
	39:  &Normal{Use: true, Origin: "ТРК Луч (Пуровск)", Various: []string{"ТРК Луч (Пуровск)"}},
	40:  &Normal{Use: true, Origin: "TV 12 Gudauta Music", Various: []string{"TV 12 Gudauta Music"}},
	41:  &Normal{Use: true, Origin: "Zik TV HD", Various: []string{"Zik TV HD"}},
	42:  &Normal{Use: true, Origin: "Астрахань 24 HD", Various: []string{"Астрахань 24 HD"}},
	43:  &Normal{Use: true, Origin: "Звезда", Various: []string{"Звезда"}},
	44:  &Normal{Use: true, Origin: "Лагуна ТВ (Брест)", Various: []string{"Лагуна ТВ (Брест)"}},
	45:  &Normal{Use: true, Origin: "ОРТ Планета", Various: []string{"ОРТ Планета"}},
	46:  &Normal{Use: true, Origin: "НТС (Севастополь)", Various: []string{"НТС (Севастополь)"}},
	47:  &Normal{Use: true, Origin: "Надежда", Various: []string{"Надежда"}},
	48:  &Normal{Use: true, Origin: "Репортер (Одесса)", Various: []string{"Репортер (Одесса)"}},
	49:  &Normal{Use: true, Origin: "Россия 24 (Ульяновск)", Various: []string{"Россия 24 (Ульяновск)"}},
	50:  &Normal{Use: true, Origin: "Союз", Various: []string{"Союз"}},
	51:  &Normal{Use: true, Origin: "MTV Mix (Уфа)", Various: []string{"MTV Mix (Уфа)"}},
	52:  &Normal{Use: true, Origin: "Publika TV HD (Moldova)", Various: []string{"Publika TV HD (Moldova)"}},
	53:  &Normal{Use: true, Origin: "TV1 KG", Various: []string{"TV1 KG"}},
	54:  &Normal{Use: true, Origin: "UA TV HD", Various: []string{"UA TV HD"}},
	55:  &Normal{Use: true, Origin: "Аист ТВ (Иркутск)", Various: []string{"Аист ТВ (Иркутск)"}},
	56:  &Normal{Use: true, Origin: "Варяг ТВ", Various: []string{"Варяг ТВ"}},
	57:  &Normal{Use: true, Origin: "Урфо 24/6 HD", Various: []string{"Урфо 24/6 HD"}},
	58:  &Normal{Use: true, Origin: "Настоящее Время HD", Various: []string{"Настоящее Время HD"}},
	59:  &Normal{Use: true, Origin: "Первый Музыкальный RU BY", Various: []string{"Первый Музыкальный RU BY"}},
	60:  &Normal{Use: true, Origin: "1+1 (HD)", Various: []string{"1+1 (HD)"}},
	61:  &Normal{Use: true, Origin: "Новое Телевидение", Various: []string{"Новое Телевидение"}},
	62:  &Normal{Use: true, Origin: "Толк ТВ (Барнаул)", Various: []string{"Толк ТВ (Барнаул)"}},
	63:  &Normal{Use: true, Origin: "DW TV English", Various: []string{"DW TV English"}},
	64:  &Normal{Use: true, Origin: "Hit Music Channel", Various: []string{"Hit Music Channel"}},
	65:  &Normal{Use: true, Origin: "UA Запорожье", Various: []string{"UA Запорожье"}},
	66:  &Normal{Use: true, Origin: "Медиа Информ (Одесса)", Various: []string{"Медиа Информ (Одесса)"}},
	67:  &Normal{Use: true, Origin: "Министерство идей", Various: []string{"Министерство идей"}},
	68:  &Normal{Use: true, Origin: "Первый Городской (Одесса)", Various: []string{"Первый Городской (Одесса)"}},
	69:  &Normal{Use: true, Origin: "Первый канал (РФ)", Various: []string{"Первый канал (РФ)"}},
	70:  &Normal{Use: true, Origin: "ТРК Рудана", Various: []string{"ТРК Рудана"}},
	71:  &Normal{Use: true, Origin: "Heavy Metal TV", Various: []string{"Heavy Metal TV"}},
	72:  &Normal{Use: true, Origin: "UA Донбас", Various: []string{"UA Донбас"}},
	73:  &Normal{Use: true, Origin: "ЧП Инфо", Various: []string{"ЧП Инфо"}},
	74:  &Normal{Use: true, Origin: "НТВ Молдова", Various: []string{"НТВ Молдова"}},
	75:  &Normal{Use: true, Origin: "Украина", Various: []string{"Украина"}},
	76:  &Normal{Use: true, Origin: "8 канал (Беларусь)", Various: []string{"8 канал (Беларусь)"}},
	77:  &Normal{Use: true, Origin: "ATR", Various: []string{"ATR"}},
	78:  &Normal{Use: true, Origin: "Almaty TV (KZ)", Various: []string{"Almaty TV (KZ)"}},
	79:  &Normal{Use: true, Origin: "En TV/ZOOM (Энергодар)", Various: []string{"En TV/ZOOM (Энергодар)"}},
	80:  &Normal{Use: true, Origin: "Беларусь 24", Various: []string{"Беларусь 24"}},
	81:  &Normal{Use: true, Origin: "Общественное Независимое ТВ", Various: []string{"Общественное Независимое ТВ"}},
	82:  &Normal{Use: true, Origin: "Свое ТВ (Ставрополь)", Various: []string{"Свое ТВ (Ставрополь)"}},
	83:  &Normal{Use: true, Origin: "Akudji TV HD (Резерв)", Various: []string{"Akudji TV HD (Резерв)"}},
	84:  &Normal{Use: true, Origin: "HD Fashion & Lifestyle UA", Various: []string{"HD Fashion & Lifestyle UA"}},
	85:  &Normal{Use: true, Origin: "Кавказ 24", Various: []string{"Кавказ 24"}},
	86:  &Normal{Use: true, Origin: "Мир +3 (KZ)", Various: []string{"Мир +3 (KZ)"}},
	87:  &Normal{Use: true, Origin: "ТИС ТВ (Одесса)", Various: []string{"ТИС ТВ (Одесса)"}},
	88:  &Normal{Use: true, Origin: "Экспресс (Пенза)", Various: []string{"Экспресс (Пенза)"}},
	89:  &Normal{Use: true, Origin: "1Music Channel Hungary", Various: []string{"1Music Channel Hungary"}},
	90:  &Normal{Use: true, Origin: "5 канал (Украина)", Various: []string{"5 канал (Украина)"}},
	91:  &Normal{Use: true, Origin: "Radio Capital TV", Various: []string{"Radio Capital TV"}},
	92:  &Normal{Use: true, Origin: "Любимое TV", Various: []string{"Любимое TV"}},
	93:  &Normal{Use: true, Origin: "Моя Планета", Various: []string{"Моя Планета"}},
	94:  &Normal{Use: true, Origin: "Пинск ТВ", Various: []string{"Пинск ТВ"}},
	95:  &Normal{Use: true, Origin: "HD Media 3D", Various: []string{"HD Media 3D"}},
	96:  &Normal{Use: true, Origin: "Еко TV", Various: []string{"Еко TV"}},
	97:  &Normal{Use: true, Origin: "Одеса", Various: []string{"Одеса"}},
	98:  &Normal{Use: true, Origin: "Рика ТВ", Various: []string{"Рика ТВ"}},
	99:  &Normal{Use: true, Origin: "ТВЦ", Various: []string{"ТВЦ"}},
	100: &Normal{Use: true, Origin: "Урал-Информ ТВ (Пермь)", Various: []string{"Урал-Информ ТВ (Пермь)"}},
	101: &Normal{Use: true, Origin: "Крым 1", Various: []string{"Крым 1"}},
	102: &Normal{Use: true, Origin: "Миллет", Various: []string{"Миллет"}},
	103: &Normal{Use: true, Origin: "Радио Маяк (Веб-камера)", Various: []string{"Радио Маяк (Веб-камера)"}},
	104: &Normal{Use: true, Origin: "Южная Волна HD", Various: []string{"Южная Волна HD"}},
	105: &Normal{Use: true, Origin: "8 Канал (Красноярский край)", Various: []string{"8 Канал (Красноярский край)"}},
	106: &Normal{Use: true, Origin: "UA Кропивницкий", Various: []string{"UA Кропивницкий"}},
	107: &Normal{Use: true, Origin: "VRT.TV", Various: []string{"VRT.TV"}},
	108: &Normal{Use: true, Origin: "Odessa Fashion TV", Various: []string{"Odessa Fashion TV"}},
	109: &Normal{Use: true, Origin: "STV (Одесса)", Various: []string{"STV (Одесса)"}},
	110: &Normal{Use: true, Origin: "Sochi 24 HD", Various: []string{"Sochi 24 HD"}},
	111: &Normal{Use: true, Origin: "Еспресо TV", Various: []string{"Еспресо TV"}},
	112: &Normal{Use: true, Origin: "Мариупольское ТВ", Various: []string{"Мариупольское ТВ"}},
	113: &Normal{Use: true, Origin: "Алекс TV (Запорожье)", Various: []string{"Алекс TV (Запорожье)"}},
	114: &Normal{Use: true, Origin: "Барс ТВ", Various: []string{"Барс ТВ"}},
	115: &Normal{Use: true, Origin: "Мир 24", Various: []string{"Мир 24"}},
	116: &Normal{Use: true, Origin: "Север ТВ (Нарьян-Мар)", Various: []string{"Север ТВ (Нарьян-Мар)"}},
	117: &Normal{Use: true, Origin: "ОТВ (Днепр)", Various: []string{"ОТВ (Днепр)"}},
	118: &Normal{Use: true, Origin: "RU TV", Various: []string{"RU TV"}},
	119: &Normal{Use: true, Origin: "Асыл Арна", Various: []string{"Асыл Арна"}},
	120: &Normal{Use: true, Origin: "Твое ТВ (Казахстан)", Various: []string{"Твое ТВ (Казахстан)"}},
	121: &Normal{Use: true, Origin: "Эфир ТВ (Казань)", Various: []string{"Эфир ТВ (Казань)"}},
	122: &Normal{Use: true, Origin: "Липецкое Время", Various: []string{"Липецкое Время"}},
	123: &Normal{Use: true, Origin: "МузСоюз", Various: []string{"МузСоюз"}},
	124: &Normal{Use: true, Origin: "Русский Север (Вологда)", Various: []string{"Русский Север (Вологда)"}},
	125: &Normal{Use: true, Origin: "ID Fashion HD", Various: []string{"ID Fashion HD"}},
	126: &Normal{Use: true, Origin: "Пингвин Лоло", Various: []string{"Пингвин Лоло"}},
	127: &Normal{Use: true, Origin: "Ратник ТВ", Various: []string{"Ратник ТВ"}},
	128: &Normal{Use: true, Origin: "AD SPORT 1 HD", Various: []string{"AD SPORT 1 HD"}},
	129: &Normal{Use: true, Origin: "Xsport TV HD", Various: []string{"Xsport TV HD"}},
	130: &Normal{Use: true, Origin: "Кубань 24 Орбита", Various: []string{"Кубань 24 Орбита"}},
	131: &Normal{Use: true, Origin: "ОТР", Various: []string{"ОТР"}},
	132: &Normal{Use: true, Origin: "Халык Арна", Various: []string{"Халык Арна"}},
	133: &Normal{Use: true, Origin: "UA Днепр", Various: []string{"UA Днепр"}},
	134: &Normal{Use: true, Origin: "Астрахань.Ru Sport HD", Various: []string{"Астрахань.Ru Sport HD"}},
	135: &Normal{Use: true, Origin: "Дисконт", Various: []string{"Дисконт"}},
	136: &Normal{Use: true, Origin: "ОТВ-Прим", Various: []string{"ОТВ-Прим"}},
	137: &Normal{Use: true, Origin: "Орбита", Various: []string{"Орбита"}},
	138: &Normal{Use: true, Origin: "Домашний (РФ)", Various: []string{"Домашний (РФ)"}},
	139: &Normal{Use: true, Origin: "Ескулап-TV", Various: []string{"Ескулап-TV"}},
	140: &Normal{Use: true, Origin: "Июнь ТВ HD (Междуреченск)", Various: []string{"Июнь ТВ HD (Междуреченск)"}},
	141: &Normal{Use: true, Origin: "Черноморская ТРК", Various: []string{"Черноморская ТРК"}},
	142: &Normal{Use: true, Origin: "Шаян ТВ HD", Various: []string{"Шаян ТВ HD"}},
	143: &Normal{Use: true, Origin: "Юнион ТВ", Various: []string{"Юнион ТВ"}},
	144: &Normal{Use: true, Origin: "City TV (BG)", Various: []string{"City TV (BG)"}},
	145: &Normal{Use: true, Origin: "G TV (Одесса)", Various: []string{"G TV (Одесса)"}},
	146: &Normal{Use: true, Origin: "Russian Music Box", Various: []string{"Russian Music Box"}},
	147: &Normal{Use: true, Origin: "UA Культура", Various: []string{"UA Культура"}},
	148: &Normal{Use: true, Origin: "А1 (Одесса)", Various: []string{"А1 (Одесса)"}},
	149: &Normal{Use: true, Origin: "Вместе РФ HD", Various: []string{"Вместе РФ HD"}},
	150: &Normal{Use: true, Origin: "К1", Various: []string{"К1"}},
	151: &Normal{Use: true, Origin: "Волгоград 24", Various: []string{"Волгоград 24"}},
	152: &Normal{Use: true, Origin: "Думская TV HD (Одесса)", Various: []string{"Думская TV HD (Одесса)"}},
	153: &Normal{Use: true, Origin: "Катунь 24", Various: []string{"Катунь 24"}},
	154: &Normal{Use: true, Origin: "М2", Various: []string{"М2"}},
	155: &Normal{Use: true, Origin: "Твой Плюс (Херсон)", Various: []string{"Твой Плюс (Херсон)"}},
	156: &Normal{Use: true, Origin: "Вариант ТВ (Владимир)", Various: []string{"Вариант ТВ (Владимир)"}},
	157: &Normal{Use: true, Origin: "Губерния (Хабаровск)", Various: []string{"Губерния (Хабаровск)"}},
	158: &Normal{Use: true, Origin: "Россия 1 HD", Various: []string{"Россия 1 HD"}},
	159: &Normal{Use: true, Origin: "8 канал Владивосток", Various: []string{"8 канал Владивосток"}},
	160: &Normal{Use: true, Origin: "Balti TV (MD)", Various: []string{"Balti TV (MD)"}},
	161: &Normal{Use: true, Origin: "Bridge TV Русский хит", Various: []string{"Bridge TV Русский хит"}},
	162: &Normal{Use: true, Origin: "ОТВ (Серпухов)", Various: []string{"ОТВ (Серпухов)"}},
	163: &Normal{Use: true, Origin: "KRATU (Херсон)", Various: []string{"KRATU (Херсон)"}},
	164: &Normal{Use: true, Origin: "Мисто плюс", Various: []string{"Мисто плюс"}},
	165: &Normal{Use: true, Origin: "Наш Дом (Пенза)", Various: []string{"Наш Дом (Пенза)"}},
	166: &Normal{Use: true, Origin: "Центральный ТВ (Полтава)", Various: []string{"Центральный ТВ (Полтава)"}},
	167: &Normal{Use: true, Origin: "8 Канал (Европа)", Various: []string{"8 Канал (Европа)"}},
	168: &Normal{Use: true, Origin: "TV7+", Various: []string{"TV7+"}},
	169: &Normal{Use: true, Origin: "ОТБ Галичина", Various: []string{"ОТБ Галичина"}},
	170: &Normal{Use: true, Origin: "Первый Западный (Львов)", Various: []string{"Первый Западный (Львов)"}},
	171: &Normal{Use: true, Origin: "Черновцы ТВ", Various: []string{"Черновцы ТВ"}},
	172: &Normal{Use: true, Origin: "OTV Music", Various: []string{"OTV Music"}},
	173: &Normal{Use: true, Origin: "Ocko Expres", Various: []string{"Ocko Expres"}},
	174: &Normal{Use: true, Origin: "Radio 105 Network TV", Various: []string{"Radio 105 Network TV"}},
	175: &Normal{Use: true, Origin: "Рен ТВ International", Various: []string{"Рен ТВ International"}},
	176: &Normal{Use: true, Origin: "Россия К", Various: []string{"Россия К"}},
	177: &Normal{Use: true, Origin: "78 канал HD", Various: []string{"78 канал HD"}},
	178: &Normal{Use: true, Origin: "Atameken Business TV (KZ)", Various: []string{"Atameken Business TV (KZ)"}},
	179: &Normal{Use: true, Origin: "UA Полтава", Various: []string{"UA Полтава"}},
	180: &Normal{Use: true, Origin: "Сила ТВ HD", Various: []string{"Сила ТВ HD"}},
	181: &Normal{Use: true, Origin: "Bridge TV", Various: []string{"Bridge TV"}},
	182: &Normal{Use: true, Origin: "Shopping Live", Various: []string{"Shopping Live"}},
	183: &Normal{Use: true, Origin: "Москва 24", Various: []string{"Москва 24"}},
	184: &Normal{Use: true, Origin: "Новое Радио ТВ", Various: []string{"Новое Радио ТВ"}},
	185: &Normal{Use: true, Origin: "ID Fashion (KZ)", Various: []string{"ID Fashion (KZ)"}},
	186: &Normal{Use: true, Origin: "ON TV (KZ)", Various: []string{"ON TV (KZ)"}},
	187: &Normal{Use: true, Origin: "VOTV", Various: []string{"VOTV"}},
	188: &Normal{Use: true, Origin: "СК1 HD (Житомир)", Various: []string{"СК1 HD (Житомир)"}},
	189: &Normal{Use: true, Origin: "Спас", Various: []string{"Спас"}},
	190: &Normal{Use: true, Origin: "Prime Time (Одесса)", Various: []string{"Prime Time (Одесса)"}},
	191: &Normal{Use: true, Origin: "АТВ (Ставрополь)", Various: []string{"АТВ (Ставрополь)"}},
	192: &Normal{Use: true, Origin: "Киевская Русь", Various: []string{"Киевская Русь"}},
	193: &Normal{Use: true, Origin: "Крым 24", Various: []string{"Крым 24"}},
	194: &Normal{Use: true, Origin: "Ocean TV", Various: []string{"Ocean TV"}},
	195: &Normal{Use: true, Origin: "Россия 1", Various: []string{"Россия 1"}},
	196: &Normal{Use: true, Origin: "Самара ГИС", Various: []string{"Самара ГИС"}},
	197: &Normal{Use: true, Origin: "Zab TV (Чита)", Various: []string{"Zab TV (Чита)"}},
	198: &Normal{Use: true, Origin: "Макси ТВ/НАШ", Various: []string{"Макси ТВ/НАШ"}},
	199: &Normal{Use: true, Origin: "Song TV Russia", Various: []string{"Song TV Russia"}},
	200: &Normal{Use: true, Origin: "UA Одесса", Various: []string{"UA Одесса"}},
	201: &Normal{Use: true, Origin: "НТН", Various: []string{"НТН"}},
	202: &Normal{Use: true, Origin: "Шансон ТВ", Various: []string{"Шансон ТВ"}},
	203: &Normal{Use: true, Origin: "Akudji TV HD", Various: []string{"Akudji TV HD"}},
	204: &Normal{Use: true, Origin: "Тюменское Время", Various: []string{"Тюменское Время"}},
	205: &Normal{Use: true, Origin: "7 канал HD (Одесса)", Various: []string{"7 канал HD (Одесса)"}},
	206: &Normal{Use: true, Origin: "TBN Украина", Various: []string{"TBN Украина"}},
	207: &Normal{Use: true, Origin: "Крик ТВ", Various: []string{"Крик ТВ"}},
	208: &Normal{Use: true, Origin: "Наше TV", Various: []string{"Наше TV"}},
	209: &Normal{Use: true, Origin: "Светлое ТВ (Global)", Various: []string{"Светлое ТВ (Global)"}},
	210: &Normal{Use: true, Origin: "Премьера TV", Various: []string{"Премьера TV"}},
	211: &Normal{Use: true, Origin: "СТВ Казахстан", Various: []string{"СТВ Казахстан"}},
	212: &Normal{Use: true, Origin: "UA Херсон", Various: []string{"UA Херсон"}},
	213: &Normal{Use: true, Origin: "Неизвестная планета", Various: []string{"Неизвестная планета"}},
	214: &Normal{Use: true, Origin: "Радость Моя", Various: []string{"Радость Моя"}},
	215: &Normal{Use: true, Origin: "ТВА Черновцы", Various: []string{"ТВА Черновцы"}},
	216: &Normal{Use: true, Origin: "43 канал HD", Various: []string{"43 канал HD"}},
	217: &Normal{Use: true, Origin: "CGTN Русский", Various: []string{"CGTN Русский"}},
	218: &Normal{Use: true, Origin: "TV5 (Запорожье)", Various: []string{"TV5 (Запорожье)"}},
	219: &Normal{Use: true, Origin: "Киев ТВ", Various: []string{"Киев ТВ"}},
	220: &Normal{Use: true, Origin: "НТМ HD (Мордовия)", Various: []string{"НТМ HD (Мордовия)"}},
	221: &Normal{Use: true, Origin: "Retro Music TV", Various: []string{"Retro Music TV"}},
	222: &Normal{Use: true, Origin: "ИТВ (Крым)", Various: []string{"ИТВ (Крым)"}},
	223: &Normal{Use: true, Origin: "Новый Мир", Various: []string{"Новый Мир"}},
	224: &Normal{Use: true, Origin: "ТНВ Планета", Various: []string{"ТНВ Планета"}},
	225: &Normal{Use: true, Origin: "34 канал", Various: []string{"34 канал"}},
	226: &Normal{Use: true, Origin: "LALE", Various: []string{"LALE"}},
	227: &Normal{Use: true, Origin: "PZN Stream", Various: []string{"PZN Stream"}},
	228: &Normal{Use: true, Origin: "Глас (Одесса)", Various: []string{"Глас (Одесса)"}},
	229: &Normal{Use: true, Origin: "ТК Алмазный край", Various: []string{"ТК Алмазный край"}},
	230: &Normal{Use: true, Origin: "Ветта 24", Various: []string{"Ветта 24"}},
	231: &Normal{Use: true, Origin: "С1 (Сургут)", Various: []string{"С1 (Сургут)"}},
	232: &Normal{Use: true, Origin: "360 Новости HD", Various: []string{"360 Новости HD"}},
	233: &Normal{Use: true, Origin: "Simon TV (Харьков)", Various: []string{"Simon TV (Харьков)"}},
	234: &Normal{Use: true, Origin: "НВК Саха", Various: []string{"НВК Саха"}},
	235: &Normal{Use: true, Origin: "ОНТ.BY", Various: []string{"ОНТ.BY"}},
	236: &Normal{Use: true, Origin: "100% News", Various: []string{"100% News"}},
	237: &Normal{Use: true, Origin: "11 канал (Днепр)", Various: []string{"11 канал (Днепр)"}},
	238: &Normal{Use: true, Origin: "Hromadske TV UA", Various: []string{"Hromadske TV UA"}},
	239: &Normal{Use: true, Origin: "UA Житомир", Various: []string{"UA Житомир"}},
	240: &Normal{Use: true, Origin: "Дайвинг TV", Various: []string{"Дайвинг TV"}},
	241: &Normal{Use: true, Origin: "Надия/Новый канал (Харьков.обл.)", Various: []string{"Надия/Новый канал (Харьков.обл.)"}},
	242: &Normal{Use: true, Origin: "Тверской проспект", Various: []string{"Тверской проспект"}},
	243: &Normal{Use: true, Origin: "Ювелирочка", Various: []string{"Ювелирочка"}},
	244: &Normal{Use: true, Origin: "7 канал (KZ)", Various: []string{"7 канал (KZ)"}},
	245: &Normal{Use: true, Origin: "Губерния Самара", Various: []string{"Губерния Самара"}},
	246: &Normal{Use: true, Origin: "Вера 24", Various: []string{"Вера 24"}},
	247: &Normal{Use: true, Origin: "Первый Деловой", Various: []string{"Первый Деловой"}},
	248: &Normal{Use: true, Origin: "ТРК 555 (Алушта)", Various: []string{"ТРК 555 (Алушта)"}},
	249: &Normal{Use: true, Origin: "Sirius TV", Various: []string{"Sirius TV"}},
	250: &Normal{Use: true, Origin: "Univer TV", Various: []string{"Univer TV"}},
	251: &Normal{Use: true, Origin: "Град ТВ (Одесса)", Various: []string{"Град ТВ (Одесса)"}},
	252: &Normal{Use: true, Origin: "Astana TV", Various: []string{"Astana TV"}},
	253: &Normal{Use: true, Origin: "Music Box UA", Various: []string{"Music Box UA"}},
	254: &Normal{Use: true, Origin: "Дон 24 HD", Various: []string{"Дон 24 HD"}},
	255: &Normal{Use: true, Origin: "Первый Городской (Калининград)", Various: []string{"Первый Городской (Калининград)"}},
	256: &Normal{Use: true, Origin: "Прямой HD", Various: []string{"Прямой HD"}},
	257: &Normal{Use: true, Origin: "Татарстан 24", Various: []string{"Татарстан 24"}},
	258: &Normal{Use: true, Origin: "TV Brics", Various: []string{"TV Brics"}},
	259: &Normal{Use: true, Origin: "Абаза ТВ", Various: []string{"Абаза ТВ"}},
	260: &Normal{Use: true, Origin: "Правда ТУТ Львов", Various: []string{"Правда ТУТ Львов"}},
	261: &Normal{Use: true, Origin: "Арис 24", Various: []string{"Арис 24"}},
	262: &Normal{Use: true, Origin: "КТК", Various: []string{"КТК"}},
	263: &Normal{Use: true, Origin: "360 HD", Various: []string{"360 HD"}},
	264: &Normal{Use: true, Origin: "Pingvini Ukas (EE)", Various: []string{"Pingvini Ukas (EE)"}},
	265: &Normal{Use: true, Origin: "Солнечногорское ТВ", Various: []string{"Солнечногорское ТВ"}},
	266: &Normal{Use: true, Origin: "ТКР (Рязань)", Various: []string{"ТКР (Рязань)"}},
	267: &Normal{Use: true, Origin: "33 канал", Various: []string{"33 канал"}},
	268: &Normal{Use: true, Origin: "TV Губерния (Воронеж)", Various: []string{"TV Губерния (Воронеж)"}},
	269: &Normal{Use: true, Origin: "Аверс ТВ (Луцк)", Various: []string{"Аверс ТВ (Луцк)"}},
	270: &Normal{Use: true, Origin: "РБК ТВ", Various: []string{"РБК ТВ"}},
	271: &Normal{Use: true, Origin: "Nano TV", Various: []string{"Nano TV"}},
	272: &Normal{Use: true, Origin: "STR TV", Various: []string{"STR TV"}},
	273: &Normal{Use: true, Origin: "UA Перший HD [Геоблок]", Various: []string{"UA Перший HD [Геоблок]"}},
	274: &Normal{Use: true, Origin: "Калейдоскоп ТВ", Various: []string{"Калейдоскоп ТВ"}},
	275: &Normal{Use: true, Origin: "Радио Хит (Орск)", Various: []string{"Радио Хит (Орск)"}},
	276: &Normal{Use: true, Origin: "8 Канал", Various: []string{"8 Канал"}},
	277: &Normal{Use: true, Origin: "86 канал (Сургут)", Various: []string{"86 канал (Сургут)"}},
	278: &Normal{Use: true, Origin: "4 канал Украина", Various: []string{"4 канал Украина"}},
	279: &Normal{Use: true, Origin: "7 TV", Various: []string{"7 TV"}},
	280: &Normal{Use: true, Origin: "Bambarbia TV HD", Various: []string{"Bambarbia TV HD"}},
	281: &Normal{Use: true, Origin: "Deejay TV", Various: []string{"Deejay TV"}},
	282: &Normal{Use: true, Origin: "HD Media", Various: []string{"HD Media"}},
	283: &Normal{Use: true, Origin: "ICTV [Геоблок]", Various: []string{"ICTV [Геоблок]"}},
	284: &Normal{Use: true, Origin: "Radio Monte Carlo TV", Various: []string{"Radio Monte Carlo TV"}},
	285: &Normal{Use: true, Origin: "Хабар", Various: []string{"Хабар"}},
	286: &Normal{Use: true, Origin: "Синергия ТВ", Various: []string{"Синергия ТВ"}},
	287: &Normal{Use: true, Origin: "Точка ТВ", Various: []string{"Точка ТВ"}},
	288: &Normal{Use: true, Origin: "Pro 100 TV", Various: []string{"Pro 100 TV"}},
	289: &Normal{Use: true, Origin: "TV8 HD Moldova", Various: []string{"TV8 HD Moldova"}},
	290: &Normal{Use: true, Origin: "Интер", Various: []string{"Интер"}},
	291: &Normal{Use: true, Origin: "Мамонтенок", Various: []string{"Мамонтенок"}},
	292: &Normal{Use: true, Origin: "Херсон плюс", Various: []string{"Херсон плюс"}},
	293: &Normal{Use: true, Origin: "Якутия 24", Various: []string{"Якутия 24"}},
	294: &Normal{Use: true, Origin: "Первый Музыкальный UHD BY", Various: []string{"Первый Музыкальный UHD BY"}},
	295: &Normal{Use: true, Origin: "Россия 1 (Чувашия)", Various: []string{"Россия 1 (Чувашия)"}},
	296: &Normal{Use: true, Origin: "9 канал (Днепр)", Various: []string{"9 канал (Днепр)"}},
	297: &Normal{Use: true, Origin: "Cars & Stars TV HD", Various: []string{"Cars & Stars TV HD"}},
	298: &Normal{Use: true, Origin: "NRJ Hits TV HD", Various: []string{"NRJ Hits TV HD"}},
	299: &Normal{Use: true, Origin: "UA Чернигов", Various: []string{"UA Чернигов"}},
	300: &Normal{Use: true, Origin: "Классика кино", Various: []string{"Классика кино"}},
	301: &Normal{Use: true, Origin: "Донеччина TV", Various: []string{"Донеччина TV"}},
	302: &Normal{Use: true, Origin: "Кузбасс 24", Various: []string{"Кузбасс 24"}},
	303: &Normal{Use: true, Origin: "Надия", Various: []string{"Надия"}},
	304: &Normal{Use: true, Origin: "Городской телеканал (Ярославль)", Various: []string{"Городской телеканал (Ярославль)"}},
	305: &Normal{Use: true, Origin: "Первый Метео", Various: []string{"Первый Метео"}},
	306: &Normal{Use: true, Origin: "Первый Музыкальный RU HD BY", Various: []string{"Первый Музыкальный RU HD BY"}},
	307: &Normal{Use: true, Origin: "112 Украина HD", Various: []string{"112 Украина HD"}},
	308: &Normal{Use: true, Origin: "A2", Various: []string{"A2"}},
	309: &Normal{Use: true, Origin: "Sochi Live HD", Various: []string{"Sochi Live HD"}},
	310: &Normal{Use: true, Origin: "360 (Сургут)", Various: []string{"360 (Сургут)"}},
	311: &Normal{Use: true, Origin: "Most Video TV HD", Various: []string{"Most Video TV HD"}},
	312: &Normal{Use: true, Origin: "UA Подолье", Various: []string{"UA Подолье"}},
	313: &Normal{Use: true, Origin: "Вкусное ТВ", Various: []string{"Вкусное ТВ"}},
	314: &Normal{Use: true, Origin: "Хабар 24", Various: []string{"Хабар 24"}},
	315: &Normal{Use: true, Origin: "Bridge TV Deluxe", Various: []string{"Bridge TV Deluxe"}},
	316: &Normal{Use: true, Origin: "Россия 24", Various: []string{"Россия 24"}},
	317: &Normal{Use: true, Origin: "12 Канал (Омск)", Various: []string{"12 Канал (Омск)"}},
	318: &Normal{Use: true, Origin: "Renome (Одесса)", Various: []string{"Renome (Одесса)"}},
	319: &Normal{Use: true, Origin: "Продвижение", Various: []string{"Продвижение"}},
	320: &Normal{Use: true, Origin: "WFC TV HD", Various: []string{"WFC TV HD"}},
	321: &Normal{Use: true, Origin: "Енисей", Various: []string{"Енисей"}},
	322: &Normal{Use: true, Origin: "ПРНК", Various: []string{"ПРНК"}},
	323: &Normal{Use: true, Origin: "Первый Музыкальный HD BY", Various: []string{"Первый Музыкальный HD BY"}},
	324: &Normal{Use: true, Origin: "Ocko", Various: []string{"Ocko"}},
	325: &Normal{Use: true, Origin: "К16 (Саров)", Various: []string{"К16 (Саров)"}},
	326: &Normal{Use: true, Origin: "ННТВ HD", Various: []string{"ННТВ HD"}},
	327: &Normal{Use: true, Origin: "Рада ТВ", Various: []string{"Рада ТВ"}},
	328: &Normal{Use: true, Origin: "Здоровье (Одесса)", Various: []string{"Здоровье (Одесса)"}},
	329: &Normal{Use: true, Origin: "Курай ТВ", Various: []string{"Курай ТВ"}},
	330: &Normal{Use: true, Origin: "HTV KG", Various: []string{"HTV KG"}},
	331: &Normal{Use: true, Origin: "Селенга ТВ", Various: []string{"Селенга ТВ"}},
	332: &Normal{Use: true, Origin: "4Fun TV", Various: []string{"4Fun TV"}},
	333: &Normal{Use: true, Origin: "Leomax 24", Various: []string{"Leomax 24"}},
	334: &Normal{Use: true, Origin: "UA Перший", Various: []string{"UA Перший"}},
	335: &Normal{Use: true, Origin: "Афонтово (Красноярск)", Various: []string{"Афонтово (Красноярск)"}},
	336: &Normal{Use: true, Origin: "Вестник Надыма", Various: []string{"Вестник Надыма"}},
	337: &Normal{Use: true, Origin: "Илли ТВ", Various: []string{"Илли ТВ"}},
	338: &Normal{Use: true, Origin: "Первый Городской (Нижний Новгород)", Various: []string{"Первый Городской (Нижний Новгород)"}},
	339: &Normal{Use: true, Origin: "ТРК Евразия (Орск)", Various: []string{"ТРК Евразия (Орск)"}},
	340: &Normal{Use: true, Origin: "Третий Цифровой (Одесса)", Various: []string{"Третий Цифровой (Одесса)"}},
	341: &Normal{Use: true, Origin: "Удмуртия ТВ", Various: []string{"Удмуртия ТВ"}},
	342: &Normal{Use: true, Origin: "Ямал-Регион", Various: []string{"Ямал-Регион"}},
	343: &Normal{Use: true, Origin: "Kronehit TV HD", Various: []string{"Kronehit TV HD"}},
	344: &Normal{Use: true, Origin: "Luxury HD", Various: []string{"Luxury HD"}},
	345: &Normal{Use: true, Origin: "Pingvini Ukas (LT)", Various: []string{"Pingvini Ukas (LT)"}},
	346: &Normal{Use: true, Origin: "Song TV Armenia", Various: []string{"Song TV Armenia"}},
	347: &Normal{Use: true, Origin: "Антенна/Смела ТВ (Черкассы)", Various: []string{"Антенна/Смела ТВ (Черкассы)"}},
	348: &Normal{Use: true, Origin: "Лида ТВ", Various: []string{"Лида ТВ"}},
	349: &Normal{Use: true, Origin: "Рен ТВ", Various: []string{"Рен ТВ"}},
	350: &Normal{Use: true, Origin: "UA Сумы", Various: []string{"UA Сумы"}},
	351: &Normal{Use: true, Origin: "Нижний Новгород 24", Various: []string{"Нижний Новгород 24"}},
	352: &Normal{Use: true, Origin: "Сургут 24", Various: []string{"Сургут 24"}},
	353: &Normal{Use: true, Origin: "Ocko Star", Various: []string{"Ocko Star"}},
	354: &Normal{Use: true, Origin: "Юрган ТВ HD", Various: []string{"Юрган ТВ HD"}},
	355: &Normal{Use: true, Origin: "TV Pro", Various: []string{"TV Pro"}},
	356: &Normal{Use: true, Origin: "UA Черкассы", Various: []string{"UA Черкассы"}},
	357: &Normal{Use: true, Origin: "ТВК 24 (Красноярск)", Various: []string{"ТВК 24 (Красноярск)"}},
	358: &Normal{Use: true, Origin: "ЯТБ (Херсон)", Various: []string{"ЯТБ (Херсон)"}},
	359: &Normal{Use: true, Origin: "France 24 (ENG)", Various: []string{"France 24 (ENG)"}},
	360: &Normal{Use: true, Origin: "TVM Channel", Various: []string{"TVM Channel"}},
	361: &Normal{Use: true, Origin: "ТРК РАI", Various: []string{"ТРК РАI"}},
	362: &Normal{Use: true, Origin: "Тольятти 24", Various: []string{"Тольятти 24"}},
	363: &Normal{Use: true, Origin: "Центр Красноярск", Various: []string{"Центр Красноярск"}},
	364: &Normal{Use: true, Origin: "VIVA (Polska)", Various: []string{"VIVA (Polska)"}},
	365: &Normal{Use: true, Origin: "Евроновости", Various: []string{"Евроновости"}},
	366: &Normal{Use: true, Origin: "Первый Городской (Кривой Рог)", Various: []string{"Первый Городской (Кривой Рог)"}},
	367: &Normal{Use: true, Origin: "Россия 24 (Чита)", Various: []string{"Россия 24 (Чита)"}},
	368: &Normal{Use: true, Origin: "Скиф (Беларусь)", Various: []string{"Скиф (Беларусь)"}},
	369: &Normal{Use: true, Origin: "UA Тернополь", Various: []string{"UA Тернополь"}},
	370: &Normal{Use: true, Origin: "Астрахань.Ru TV HD", Various: []string{"Астрахань.Ru TV HD"}},
	371: &Normal{Use: true, Origin: "Витрина ТВ", Various: []string{"Витрина ТВ"}},
	372: &Normal{Use: true, Origin: "ULTO TV HD", Various: []string{"ULTO TV HD"}},
	373: &Normal{Use: true, Origin: "МТРК", Various: []string{"МТРК"}},
	374: &Normal{Use: true, Origin: "Радио Страна FM ТВ", Various: []string{"Радио Страна FM ТВ"}},
	375: &Normal{Use: true, Origin: "Dombyra TV", Various: []string{"Dombyra TV"}},
	376: &Normal{Use: true, Origin: "Radio Bruno TV", Various: []string{"Radio Bruno TV"}},
	377: &Normal{Use: true, Origin: "Top Shop TV", Various: []string{"Top Shop TV"}},
	378: &Normal{Use: true, Origin: "Первый Балтийский Муз.", Various: []string{"Первый Балтийский Муз."}},
	379: &Normal{Use: true, Origin: "Первый Псковский", Various: []string{"Первый Псковский"}},
	380: &Normal{Use: true, Origin: "Пингвин Лоло (LV)", Various: []string{"Пингвин Лоло (LV)"}},
	381: &Normal{Use: true, Origin: "ТБН", Various: []string{"ТБН"}},
	382: &Normal{Use: true, Origin: "UA Винница", Various: []string{"UA Винница"}},
	383: &Normal{Use: true, Origin: "Первый Музыкальный BY", Various: []string{"Первый Музыкальный BY"}},
	384: &Normal{Use: true, Origin: "Башкортостан 24 HD", Various: []string{"Башкортостан 24 HD"}},
	385: &Normal{Use: true, Origin: "СТРК HD", Various: []string{"СТРК HD"}},
	386: &Normal{Use: true, Origin: "24 канал HD", Various: []string{"24 канал HD"}},
	387: &Normal{Use: true, Origin: "Муниципальное Телевидение Волгограда", Various: []string{"Муниципальное Телевидение Волгограда"}},
	388: &Normal{Use: true, Origin: "ТВ Тур", Various: []string{"ТВ Тур"}},
	389: &Normal{Use: true, Origin: "8 канал (Витебск)", Various: []string{"8 канал (Витебск)"}},
	390: &Normal{Use: true, Origin: "Балта ТВ", Various: []string{"Балта ТВ"}},
	391: &Normal{Use: true, Origin: "PULSE TV", Various: []string{"PULSE TV"}},
	392: &Normal{Use: true, Origin: "Радио Шансон ТВ", Various: []string{"Радио Шансон ТВ"}},
	393: &Normal{Use: true, Origin: "Сонце", Various: []string{"Сонце"}},
	394: &Normal{Use: true, Origin: "Fresh TV", Various: []string{"Fresh TV"}},
	395: &Normal{Use: true, Origin: "Мордовия 24", Various: []string{"Мордовия 24"}},
	396: &Normal{Use: true, Origin: "ТВ-Дом (Одесса)", Various: []string{"ТВ-Дом (Одесса)"}},
	397: &Normal{Use: true, Origin: "ТВ6 (Курск)", Various: []string{"ТВ6 (Курск)"}},
	398: &Normal{Use: true, Origin: "Bridge TV Classic", Various: []string{"Bridge TV Classic"}},
	399: &Normal{Use: true, Origin: "M2O TV", Various: []string{"M2O TV"}},
	400: &Normal{Use: true, Origin: "Белгород 24", Various: []string{"Белгород 24"}},
	401: &Normal{Use: true, Origin: "СТВ-Рен ТВ (Беларусь)", Various: []string{"СТВ-Рен ТВ (Беларусь)"}},
	402: &Normal{Use: true, Origin: "Navigator TV", Various: []string{"Navigator TV"}},
	403: &Normal{Use: true, Origin: "Plus (Одесса)", Various: []string{"Plus (Одесса)"}},
	404: &Normal{Use: true, Origin: "Академия (Одесса)", Various: []string{"Академия (Одесса)"}},
	405: &Normal{Use: true, Origin: "БелРос", Various: []string{"БелРос"}},
	406: &Normal{Use: true, Origin: "Вся Уфа HD", Various: []string{"Вся Уфа HD"}},
	407: &Normal{Use: true, Origin: "НТА", Various: []string{"НТА"}},
	408: &Normal{Use: true, Origin: "CBC (AZ)", Various: []string{"CBC (AZ)"}},
	409: &Normal{Use: true, Origin: "Z TV (Запорожье)", Various: []string{"Z TV (Запорожье)"}},
	410: &Normal{Use: true, Origin: "Волжский Плюс", Various: []string{"Волжский Плюс"}},
	411: &Normal{Use: true, Origin: "Одинцово ТВ", Various: []string{"Одинцово ТВ"}},
	412: &Normal{Use: true, Origin: "ТДК 42", Various: []string{"ТДК 42"}},
	413: &Normal{Use: true, Origin: "Kino 24", Various: []string{"Kino 24"}},
	414: &Normal{Use: true, Origin: "Leomax", Various: []string{"Leomax"}},
	415: &Normal{Use: true, Origin: "UA Ровно", Various: []string{"UA Ровно"}},
	416: &Normal{Use: true, Origin: "Конный Мир", Various: []string{"Конный Мир"}},
	417: &Normal{Use: true, Origin: "Севастополь 24", Various: []string{"Севастополь 24"}},
	418: &Normal{Use: true, Origin: "Brodilo TV HD", Various: []string{"Brodilo TV HD"}},
	419: &Normal{Use: true, Origin: "Tamasha TV (KZ)", Various: []string{"Tamasha TV (KZ)"}},
	420: &Normal{Use: true, Origin: "UA Буковина", Various: []string{"UA Буковина"}},
	421: &Normal{Use: true, Origin: "Известия ТВ HD", Various: []string{"Известия ТВ HD"}},
	422: &Normal{Use: true, Origin: "Релакс TV", Various: []string{"Релакс TV"}},
	423: &Normal{Use: true, Origin: "1HD Music TV", Various: []string{"1HD Music TV"}},
	424: &Normal{Use: true, Origin: "RU TV HD", Various: []string{"RU TV HD"}},
	425: &Normal{Use: true, Origin: "UA Волынь", Various: []string{"UA Волынь"}},
	426: &Normal{Use: true, Origin: "НТК Украина", Various: []string{"НТК Украина"}},
	427: &Normal{Use: true, Origin: "Первый канал HD", Various: []string{"Первый канал HD"}},
	428: &Normal{Use: true, Origin: "Эхо ТВ 24 (Новоуральск)", Various: []string{"Эхо ТВ 24 (Новоуральск)"}},
	429: &Normal{Use: true, Origin: "RTL 102.5 TV", Various: []string{"RTL 102.5 TV"}},
	430: &Normal{Use: true, Origin: "Travel Guide TV", Various: []string{"Travel Guide TV"}},
	431: &Normal{Use: true, Origin: "Скат 24", Various: []string{"Скат 24"}},
	432: &Normal{Use: true, Origin: "Accent TV Moldova", Various: []string{"Accent TV Moldova"}},
	433: &Normal{Use: true, Origin: "UA Николаев", Various: []string{"UA Николаев"}},
	434: &Normal{Use: true, Origin: "Правда ТУТ HD", Various: []string{"Правда ТУТ HD"}},
	435: &Normal{Use: true, Origin: "Просвещение", Various: []string{"Просвещение"}},
	436: &Normal{Use: true, Origin: "Россия РТР", Various: []string{"Россия РТР"}},
	437: &Normal{Use: true, Origin: "UA Львов", Various: []string{"UA Львов"}},
	438: &Normal{Use: true, Origin: "Инший (Одесса)", Various: []string{"Инший (Одесса)"}},
	439: &Normal{Use: true, Origin: "Киноменю HD", Various: []string{"Киноменю HD"}},
	440: &Normal{Use: true, Origin: "Дагестан ТВ", Various: []string{"Дагестан ТВ"}},
	441: &Normal{Use: true, Origin: "Осетия-Ирыстон", Various: []string{"Осетия-Ирыстон"}},
	442: &Normal{Use: true, Origin: "Смайлик ТВ HD", Various: []string{"Смайлик ТВ HD"}},
	443: &Normal{Use: true, Origin: "E TV HD", Various: []string{"E TV HD"}},
	444: &Normal{Use: true, Origin: "WFC TV International HD", Various: []string{"WFC TV International HD"}},
	445: &Normal{Use: true, Origin: "БСТ", Various: []string{"БСТ"}},
	446: &Normal{Use: true, Origin: "Ел Арна", Various: []string{"Ел Арна"}},
	447: &Normal{Use: true, Origin: "Правда ТУТ Киев", Various: []string{"Правда ТУТ Киев"}},
	448: &Normal{Use: true, Origin: "ТНТ Music", Various: []string{"ТНТ Music"}},
	449: &Normal{Use: true, Origin: "Телплюс ТВ (Астрахань)", Various: []string{"Телплюс ТВ (Астрахань)"}},
	450: &Normal{Use: true, Origin: "ACB TV", Various: []string{"ACB TV"}},
	451: &Normal{Use: true, Origin: "Мультимания LV", Various: []string{"Мультимания LV"}},
	452: &Normal{Use: true, Origin: "Севастополь ТВ", Various: []string{"Севастополь ТВ"}},
	453: &Normal{Use: true, Origin: "Союз TV (Житомир)", Various: []string{"Союз TV (Житомир)"}},
	454: &Normal{Use: true, Origin: "ТРК Круг (Одесса)", Various: []string{"ТРК Круг (Одесса)"}},
	455: &Normal{Use: true, Origin: "Три Ангела", Various: []string{"Три Ангела"}},
	456: &Normal{Use: true, Origin: "Беларусь 4 (Могилев)", Various: []string{"Беларусь 4 (Могилев)"}},
	457: &Normal{Use: true, Origin: "Kazakh TV (RU)", Various: []string{"Kazakh TV (RU)"}},
	458: &Normal{Use: true, Origin: "Красная линия ТВ", Various: []string{"Красная линия ТВ"}},
	459: &Normal{Use: true, Origin: "Мир 24 HD", Various: []string{"Мир 24 HD"}},
	460: &Normal{Use: true, Origin: "31 Канал (KZ)", Various: []string{"31 Канал (KZ)"}},
	461: &Normal{Use: true, Origin: "ИРТ (Днепр)", Various: []string{"ИРТ (Днепр)"}},
	462: &Normal{Use: true, Origin: "Матур ТВ HD", Various: []string{"Матур ТВ HD"}},

	463: &Normal{
		Use:     true,
		Origin:  "RT Документальный",
		Various: []string{"RT Документальный"},
	},
}
